### ISSUE TITLE
clj-time.coerce fails to compile on Clojure 1.6.0

### ISSUE THREAD

**Issue by jmglov** [clj-time/clj-time#124]
I'm not sure if this is new breakage or something strange about my environment, but when I try to require `clj-time.coerce`, I get a compilation error:

```
: jmglov@alhana; lein repl
nREPL server started on port 53061 on host 127.0.0.1
REPL-y 0.2.1
Clojure 1.6.0
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)

user=> (require '[clj-time.core :as dt])
nil
user=> (require '[clj-time.coerce :as c])

CompilerException java.lang.RuntimeException: Unable to resolve symbol: second in this context, compiling:(clj_time/coerce.clj:146:64) 
```

My project.clj looks like this:

```
(defproject foo "1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [cheshire "5.2.0"]
                 [clj-time "0.7.0"]
                 [compojure "1.1.6"]
                 [hiccup "1.0.5"]
                 [korma "0.3.0-RC6"]
                 [liberator "0.10.0"]
                 [mysql/mysql-connector-java "5.1.29"]
                 [org.clojure/tools.logging "0.2.6"]
                 [log4j "1.2.17" :exclusions [javax.mail/mail
                                              javax.jms/jms
                                              com.sun.jdmk/jmxtools
                                              com.sun.jmx/jmxri]]
                 [ring/ring-json "0.3.1"]
                 [ring-server "0.3.1"]]

  :plugins [[lein-ring "0.8.10"]
            [lein-beanstalk "0.2.7"]])
```
